config/routes.rb
Rails.application.routes.draw do
  root "wizards#step1"

  resources :users, except: [:new, :create] do
    collection do
      resource :wizard, path: "signup", only: [:create] do
        get :step1
        get :step2
        get :step3

        post :perform_step
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_action :load_wizard, except: :perform_step

  def perform_step
    store_wizard_params_in_session

    @wizard = load_wizard(params[:current_step])

    if @wizard.valid?
      unless @wizard.next_step
        create
        return
      end

      redirect_to action: @wizard.next_step
    else
      render @wizard.current_step
    end
  end

  def create
    if @wizard.submit
      clean_wizard_session
      redirect_to users_path
    else
      render @wizard.class.STEPS.first
    end
  end

  def step1; end
  def step2; end
  def step3; end

  private

  def clean_wizard_session
    session[session_name] = nil
  end

  def load_wizard(step_name = action_name, attributes = session[session_name])
    @wizard =
      "Users::SignupWizard::#{step_name.camelize}".constantize.new(attributes)
  end

  def session_name
    :user_sign_up_attributes
  end

  def store_wizard_params_in_session
    if session[session_name].nil?
      session[session_name] = user_wizard_params.to_h
    else
      session[session_name].merge!(user_wizard_params)
    end
  end

  def user_wizard_params
    params.require(:"users_signup_wizard_#{params[:current_step]}").permit(:email, :username, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComplexFormWizard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.slim
= link_to "Novo usuário", step1_wizard_path
table
  thead
    th Usuario
    th Email
    th Endereço
  tbody
    - @users.each do |user|
      tr
        td= user.username
        td= user.email
        td= user.address

app/views/wizards/_errors.html.slim
- if @wizard.errors.any?
  ul
    - @wizard.errors.full_messages.each do |error|
      li= error

app/views/wizards/step1.html.slim
ul
  li
    b Passo 1
  li Passo 2
  li Passo 3
= render "errors"
= form_for @wizard, url: perform_step_wizard_path do |f|
  = hidden_field_tag :current_step, @wizard.current_step
  = f.text_field :username, placeholder: "Nome de usuário"
  = f.submit "Próximo"

app/views/wizards/step2.html.slim
ul
  li= link_to "Passo 1", step1_wizard_path
  li
    b Passo 2
  li Passo 3
= render "errors"
= form_for @wizard, url: perform_step_wizard_path do |f|
  = hidden_field_tag :current_step, @wizard.current_step
  = f.email_field :email, placeholder: "Email"
  = f.submit "Próximo"

app/views/wizards/step3.html.slim
ul
  li= link_to "Passo 1", step1_wizard_path
  li= link_to "Passo 2", step2_wizard_path
  li
    b Passo 3
= render "errors"
= form_for @wizard, url: perform_step_wizard_path do |f|
  = hidden_field_tag :current_step, @wizard.current_step
  = f.text_field :address, placeholder: "Endereço"
  = f.submit "Próximo"